import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import NavBar from './navbar/NavBar';
import Footer from './footer/Footer';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
	title: 'Muse Metrics App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NavBar></NavBar>
				{children}
				<Footer></Footer>
			</body>
		</html>
	);
}
